# Generated by Django 5.2.1 on 2025-05-25 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reeds', '0014_remove_repertoire_reed_delete_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repertoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_title', models.CharField(default='add a title', max_length=100)),
                ('music_composer', models.CharField(null=True)),
                ('music_genre', models.CharField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('reed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repertoire_list', to='reeds.reed')),
            ],
        ),
    ]
