# Generated by Django 5.2.1 on 2025-05-14 16:09

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('photo', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('instrument', models.CharField(choices=[('Oboe', [('ob', 'Oboe'), ('da', "Oboe d'Amore"), ('ca', 'Cor Anglais'), ('bo', 'Bass Oboe'), ('hp', 'Heckelphone')]), ('Basson', [('ob', 'Basson'), ('da', 'Kontrabass Basson')]), ('Clarinet', [('BbC', 'Bb Clarinet'), ('AC', 'A Clarinet'), ('CC', 'C Clarinet'), ('EbC', 'Eb Clarinet'), ('BC', 'Bass Clarinet'), ('KC', 'Kontrabass Clarinet')]), ('Saxophone', [('SS', 'Soprano Saxophone'), ('AS', 'Alto Saxophone'), ('TS', 'Tenor Saxophone'), ('BS', 'Bass Saxophone'), ('KS', 'Kontrabass Saxophone')])], max_length=3)),
                ('char_resistance', models.IntegerField(choices=[(0, 'Soft'), (1, 'Medium'), (2, 'Hard')], default=1)),
                ('char_sound', models.IntegerField(choices=[(0, 'Shrill'), (1, 'Bright'), (2, 'Round'), (3, 'Dark'), (4, 'Dull')], default=2)),
                ('char_response', models.IntegerField(choices=[(0, 'Light'), (1, 'Accurate'), (2, 'Late')], default=1)),
                ('staple_model', models.TextField(max_length=100)),
                ('staple_length', models.FloatField()),
                ('overall_length', models.FloatField()),
                ('gauge_thickness', models.FloatField()),
                ('shaper_form', models.TextField()),
                ('cane_supplier', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Private'), (1, 'Public')], default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reed_maker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
