# Generated by Django 5.2.1 on 2025-05-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reed',
            old_name='shaper_form',
            new_name='cane_shaper_form',
        ),
        migrations.RenameField(
            model_name='reed',
            old_name='char_resistance',
            new_name='character_resistance',
        ),
        migrations.RenameField(
            model_name='reed',
            old_name='char_sound',
            new_name='character_sound',
        ),
        migrations.RenameField(
            model_name='reed',
            old_name='char_response',
            new_name='chararacter_response',
        ),
        migrations.RenameField(
            model_name='reed',
            old_name='status',
            new_name='visibility',
        ),
        migrations.AlterField(
            model_name='reed',
            name='instrument',
            field=models.CharField(choices=[('ob', 'Oboe'), ('da', "Oboe d'Amore"), ('ca', 'Cor Anglais'), ('bo', 'Bass Oboe'), ('hp', 'Heckelphone'), ('bs', 'Bassoon'), ('kb', 'Contrabassoon'), ('BbC', 'Bb Clarinet'), ('AC', 'A Clarinet'), ('CC', 'C Clarinet'), ('EbC', 'Eb Clarinet'), ('BC', 'Bass Clarinet'), ('KC', 'Contrabass Clarinet'), ('SS', 'Soprano Saxophone'), ('AS', 'Alto Saxophone'), ('TS', 'Tenor Saxophone'), ('BS', 'Bass Saxophone'), ('KS', 'Contrabass Saxophone')], max_length=4),
        ),
    ]
