# Generated by Django 5.2.1 on 2025-05-14 19:58

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeds', '0002_rename_shaper_form_reed_cane_shaper_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reed',
            name='event',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reed',
            name='repertoire',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reed',
            name='cane_shaper_form',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reed',
            name='cane_supplier',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reed',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='reed',
            name='gauge_thickness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reed',
            name='instrument',
            field=models.CharField(choices=[('ob', 'Oboe'), ('da', "Oboe d'Amore"), ('ca', 'Cor Anglais'), ('bo', 'Bass Oboe'), ('hp', 'Heckelphone'), ('bs', 'Bassoon'), ('kb', 'Contrabassoon'), ('BbC', 'Bb Clarinet'), ('AC', 'A Clarinet'), ('CC', 'C Clarinet'), ('EbC', 'Eb Clarinet'), ('BC', 'Bass Clarinet'), ('KC', 'Contrabass Clarinet'), ('SS', 'Soprano Saxophone'), ('AS', 'Alto Saxophone'), ('TS', 'Tenor Saxophone'), ('BS', 'Bass Saxophone'), ('KS', 'Contrabass Saxophone')], default='ob', max_length=4),
        ),
        migrations.AlterField(
            model_name='reed',
            name='overall_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reed',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='reed',
            name='staple_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reed',
            name='staple_model',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
