# Generated by Django 5.2.1 on 2025-05-14 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeds', '0003_reed_event_reed_repertoire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reed',
            name='event',
        ),
        migrations.RemoveField(
            model_name='reed',
            name='repertoire',
        ),
        migrations.AlterField(
            model_name='reed',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('reed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='reeds.reed')),
            ],
        ),
        migrations.CreateModel(
            name='Repertoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('composer', models.TextField(null=True)),
                ('genre', models.TextField(null=True)),
                ('reed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repertoire_list', to='reeds.reed')),
            ],
        ),
    ]
