# Generated by Django 5.2.1 on 2025-05-14 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reeds', '0004_remove_reed_event_remove_reed_repertoire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reed',
            name='photo',
        ),
    ]
