# Generated by Django 5.2.1 on 2025-05-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeds', '0006_rename_gauge_thickness_reed_cane_gauge_thickness_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='gig_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='location',
            new_name='gig_location',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='git_description',
        ),
        migrations.RenameField(
            model_name='repertoire',
            old_name='composer',
            new_name='music_composer',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.RemoveField(
            model_name='repertoire',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='repertoire',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='gig_title',
            field=models.CharField(default='a memorable occasion', max_length=100),
        ),
        migrations.AddField(
            model_name='repertoire',
            name='music_genre',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='repertoire',
            name='music_title',
            field=models.CharField(default='a favourite piece', max_length=100),
        ),
    ]
