# Generated by Django 5.2.1 on 2025-05-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeds', '0007_rename_date_event_gig_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reed',
            name='item_title',
        ),
        migrations.AlterField(
            model_name='reed',
            name='item_visibility',
            field=models.IntegerField(choices=[(0, 'Private'), (1, 'Public')], default=0),
        ),
    ]
