# Generated by Django 5.2.1 on 2025-05-15 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeds', '0009_alter_event_gig_title_alter_repertoire_music_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_gigs', to='reeds.reed'),
        ),
        migrations.AlterField(
            model_name='repertoire',
            name='reed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repertoire_list', to='reeds.reed'),
        ),
    ]
