# Generated by Django 5.2.1 on 2025-05-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeds', '0010_alter_event_reed_alter_repertoire_reed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='git_description',
            new_name='gig_description',
        ),
        migrations.AlterField(
            model_name='repertoire',
            name='music_composer',
            field=models.CharField(null=True),
        ),
    ]
