# Generated by Django 5.2.1 on 2025-05-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reeds', '0011_rename_git_description_event_gig_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reed',
            old_name='item_description',
            new_name='item_comment',
        ),
    ]
