# Generated by Django 5.2.1 on 2025-05-15 23:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeds', '0012_rename_item_description_reed_item_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='repertoire',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-15'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repertoire',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
