# Generated by Django 5.2.1 on 2025-05-25 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reeds', '0013_event_created_on_event_updated_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repertoire',
            name='reed',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Repertoire',
        ),
    ]
